---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  chart:
    spec:
      chart: airflow
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: airflow
      version: '16.6.0'
  install:
    createNamespace: true
  interval: 5m0s
  targetNamespace: airflow
  valuesFrom:
    - kind: ConfigMap
      name: airflowvalues
