#@data/values
---
auth_username: REPLACE_AUTH_USERNAME
auth_password: REPLACE_AUTH_PASSWORD
auth_fernet_key: REPLACE_AUTH_FERNET_KEY
executor: REPLACE_EXECUTOR
web_image_debug: REPLACE_WEB_IMAGE_DEBUG
scheduler_image_debug: REPLACE_SCHEDULER_IMAGE_DEBUG
scheduler_automount: REPLACE_SCHEDULER_AUTOMOUNT
worker_image_debug: REPLACE_WORKER_IMAGE_DEBUG
git_dags_enabled: REPLACE_GIT_DAGS_ENABLED
git_dags_repo: REPLACE_GIT_DAGS_REPO
git_dags_branch: REPLACE_GIT_DAGS_BRANCH
git_dags_name: REPLACE_GIT_DAGS_NAME
git_dags_path: REPLACE_GIT_DAGS_PATH
service_type: REPLACE_SERVICE_TYPE
service_port: REPLACE_SERVICE_PORT
rbac_create: REPLACE_RBAC_CREATE
redis_enabled: REPLACE_REDIS_ENABLED
main_image_tag: REPLACE_MAIN_IMAGE_TAG
metrics_image_tag: REPLACE_METRICS_IMAGE_TAG
